#!/bin/bash

if grep -q "PullCNOTs" output.txt; then
  if grep -q "BothRemotes" output.txt; then
    extension=11
  else
    extension=10
  fi
else
  if grep -q "BothRemotes" output.txt; then
    extension=01
  else
    extension=00
  fi
fi

k=$(awk -F "\"" '{print $2}' <<< `grep "k =" output.txt`)
circuit=$(awk -F ":" '{print $2}' <<< `grep "Circuit" output.txt`)"_"$k"_"$extension

T_qubits=$(awk -F ":" '{print $2}' <<< `grep "Qubits in circuit" output.txt`)
O_qubits=$(awk -F ":" '{print $2}' <<< `grep "Original qubit count" output.txt`)

ebits=$(awk -F ":" '{print $2}' <<< `grep "Total number of ebits" output.txt`)
nonLocal=$(awk -F ":" '{print $2}' <<< `grep "Non-local CNOTs" output.txt`)
T_CNOTs=$(awk -F ":" '{print $1}' <<< `grep "not, arity 1" output.txt`)
O_CNOTs=$(($T_CNOTs - $ebits * 2))

vertices=$(awk -F ":" '{print $2}' <<< `grep "Number of vertices" output.txt`)
hyperedges=$(awk -F ":" '{print $2}' <<< `grep "Number of hyperedges" output.txt`)

echo $circuit $O_CNOTs $nonLocal $ebits $O_qubits $T_qubits $vertices $hyperedges