#!/bin/bash

## Done: qft10, qft25, qft50, bwt, bfWalk (this last one only k2 and k3) [For all of the problems, k2 00 is done]

cd qft50

cd k2
cd 00
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 01
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 10
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 11
runghc ../../../getNonLocal.hs
cd ../..
echo "Progress..."

cd k3
cd 00
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 01
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 10
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 11
runghc ../../../getNonLocal.hs
cd ../..
echo "Progress..."

cd k5
cd 00
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 01
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 10
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 11
runghc ../../../getNonLocal.hs
cd ../..
echo "Progress..."

cd k7
cd 00
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 01
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 10
runghc ../../../getNonLocal.hs
cd ..
echo "Beep..."
cd 11
runghc ../../../getNonLocal.hs
cd ../..
echo "Progress..."