#!/bin/bash

thefile=../../../data.dat

cd bfWalk
cd k3/11
rm $thefile
echo Circuit CNOTs NonLocal Ebits OrigQubits TotQubits Vertices Hyperedges >> $thefile
echo "" >> $thefile
../../../getData >> $thefile
cd ../../k5/11
../../../getData >> $thefile
cd ../../k7/11
../../../getData >> $thefile
cd ../../k9/11
../../../getData >> $thefile
cd ../../k11/11
../../../getData >> $thefile
cd ../../k13/11
../../../getData >> $thefile
cd ../../k15/11
../../../getData >> $thefile
cd ../../../

cd bwt
cd k3/11
../../../getData >> $thefile
cd ../../k5/11
../../../getData >> $thefile
cd ../../k7/11
../../../getData >> $thefile
cd ../../k9/11
../../../getData >> $thefile
cd ../../k11/11
../../../getData >> $thefile
cd ../../k13/11
../../../getData >> $thefile
cd ../../k15/11
../../../getData >> $thefile
cd ../../../

cd gse
cd k3/11
../../../getData >> $thefile
cd ../../k5/11
../../../getData >> $thefile
cd ../../k7/11
../../../getData >> $thefile
cd ../../k9/11
../../../getData >> $thefile
cd ../../k11/11
../../../getData >> $thefile
cd ../../k13/11
../../../getData >> $thefile
cd ../../k15/11
../../../getData >> $thefile
cd ../../../

cd usvR
cd k3/11
../../../getData >> $thefile
cd ../../k5/11
../../../getData >> $thefile
cd ../../k7/11
../../../getData >> $thefile
cd ../../k9/11
../../../getData >> $thefile
cd ../../k11/11
../../../getData >> $thefile
cd ../../k13/11
../../../getData >> $thefile
cd ../../k15/11
../../../getData >> $thefile
cd ../../../

cd qft200
cd k3/11
../../../getData >> $thefile
cd ../../k5/11
../../../getData >> $thefile
cd ../../k7/11
../../../getData >> $thefile
cd ../../k9/11
../../../getData >> $thefile
cd ../../k11/11
../../../getData >> $thefile
cd ../../k13/11
../../../getData >> $thefile
cd ../../k15/11
../../../getData >> $thefile
cd ../../../