#!/bin/bash

thefile=../../../data.dat

cd bfWalk
cd k2
cd 00
rm $thefile
echo Circuit CNOTs NonLocal Ebits OrigQubits TotQubits Vertices Hyperedges >> $thefile
echo "" >> $thefile
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd bwt
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd gse
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd usvR
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd qft10
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd qft25
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd qft50
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd qft100
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd qft200
cd k2
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k3
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k5
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../..
cd k7
cd 00
../../../getData >> $thefile
cd ..
cd 01
../../../getData >> $thefile
cd ..
cd 10
../../../getData >> $thefile
cd ..
cd 11
../../../getData >> $thefile
cd ../../..

cd bfWalk
cd k10
cd 10
../../../getData >> $thefile
cd ../../..

cd bwt
cd k10
cd 10
../../../getData >> $thefile
cd ../../..

cd gse
cd k10
cd 01
../../../getData >> $thefile
cd ../../..

cd usvR
cd k10
cd 11
../../../getData >> $thefile
cd ../../..

cd qft200
cd k10
cd 01
../../../getData >> $thefile
cd ../../..